name: Actualizar Informacion de las cartas semanalmente

on:
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar cada domingo a medianoche
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configurar Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade requests

      - name: Actualizar informacion de las cartas
        run: |
          python -c "
          
          import requests
          import json
          import os

          url = 'https://db.ygoprodeck.com/api/v7/cardinfo.php'
          headers = {'User-Agent': 'YGOBinder/1.0 (https://github.com/TsunaHalo2001/ygobinder)'}
          response = requests.get(url, headers=headers)
          response.raise_for_status()

          os.makedirs('assets/json', exist_ok=True)
          with open('assets/json/ygo_api_cache.json', 'w', encoding='utf-8') as f:
            json.dump(response.json(), f, ensure_ascii=False, indent=2)
          "
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add assets/json/ygo_api_cache.json
          if ! git diff --staged --quiet; then
            git commit -m 'chore: Actualizar informacion de las cartas desde la API de YGOProDeck'
            git push
          else
            echo 'No hay cambios en la informacion de las cartas.'
          fi